apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
  namespace: producer
spec:
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
        - name: producer
          image: utr1903/producer
          ports:
            - protocol: TCP
              containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
                cpu: 200m
                memory: 200Mi
