apiVersion: v1
kind: Service
metadata:
  name: producer
  namespace: prod
  labels:
    app: producer
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: producer
