apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: kafka
spec:
  selector:
    matchLabels:
      app: kafka
  serviceName: kafka
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: utr1903/kafka
          command: [ "/kafka/bin/kafka-server-start.sh", "/etc/config/server.properties" ]
          ports:
            - name: client
              containerPort: 9092
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 300m
              memory: 600Mi
          readinessProbe:
            tcpSocket:
              port: 9092
            timeoutSeconds: 1
          volumeMounts:
            - name: data
              mountPath: /kafka/logs
            - name: properties
              mountPath: /etc/config
      volumes:
      - name: properties
        configMap:
          name: kafka
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
