apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: kafka
  labels:
    app: kafka
spec:
  clusterIP: None
  ports:
    - port: 9092
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: kafka
