apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  namespace: cons
spec:
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - name: consumer
          image: utr1903/consumer
          ports:
            - protocol: TCP
              containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
                cpu: 200m
                memory: 200Mi
