apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper-0
  namespace: kafka
spec:
  selector:
    matchLabels:
      app: zookeeper-0
  serviceName: zookeeper-0
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: zookeeper-0
    spec:
      containers:
        - name: zookeeper-0
          image: utr1903/zookeeper-0
          ports:
            - name: client
              containerPort: 2181
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
                cpu: 200m
                memory: 200Mi
          volumeMounts:
            - name: data
              mountPath: /kafka/logs
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
