apiVersion: v1
kind: Service
metadata:
  name: zookeeper-0
  namespace: kafka
  labels:
    app: zookeeper-0
spec:
  clusterIP: None
  ports:
    - port: 2181
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: zookeeper-0
