apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: kafka
  labels:
    app: zookeeper
spec:
  clusterIP: None
  ports:
    - port: 2181
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: zookeeper
