apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
data:
  zookeeper.properties: |
    dataDir=/kafka/logs
    clientPort={{ .Values.clientPort }}
    maxClientCnxns=0
    admin.enableServer=false
    # admin.serverPort=8080
